### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Florian-DELRIEU** [Zeviper-Gaming/WRTI-Extractor#3]
# TODO 
- [ ] Ajouter RMP Optimal "RPMOptimal" 
- [ ] Programme pour mettre les `.blkx` et les `.json` a jour
- [ ]  Angle de décrochage ( `alphaCritHigh` )

# Test a faire
> - [x] Corriger les alertes des vitesses max des flaps en fonctions de leurs disponibilité
> - [x] RPM moteur
